[CmdletBinding()]
param(
    [switch]$ImportLegacy,
    [switch]$Check,
    [string]$LegacyPkgdefPath,
    [string]$LegacyManifestPath
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path $PSScriptRoot
$srcRoot = Join-Path $repoRoot "src"
$catalogPath = Join-Path $repoRoot "catalog.json"
$pkgdefPath = Join-Path $srcRoot "icons.pkgdef"
$manifestPath = Join-Path $srcRoot "Monikers.imagemanifest"
$extensionsPath = Join-Path $repoRoot "FileExtensions.md"
$utf8 = [System.Text.UTF8Encoding]::new($false)

function Write-GeneratedFile {
    param(
        [string]$Path,
        [string]$Content
    )

    $normalized = $Content.TrimEnd() + "`r`n"

    if ($Check) {
        if (-not (Test-Path $Path)) {
            throw "Generated file is missing: $Path"
        }

        $existing = [System.IO.File]::ReadAllText($Path)
        if ($existing -ne $normalized) {
            throw "Generated file is out of date: $Path. Run tools\Generate-Catalog.ps1."
        }

        return
    }

    [System.IO.File]::WriteAllText($Path, $normalized, $utf8)
}

function Get-KnownMonikerNames {
    $assetsPath = Join-Path $srcRoot "obj\project.assets.json"
    if (-not (Test-Path $assetsPath)) {
        return $null
    }

    $assets = Get-Content $assetsPath -Raw | ConvertFrom-Json
    $library = $assets.libraries.PSObject.Properties |
        Where-Object Name -like "Microsoft.VisualStudio.ImageCatalog/*" |
        Select-Object -First 1

    if (-not $library) {
        return $null
    }

    $packageFolder = $assets.packageFolders.PSObject.Properties.Name | Select-Object -First 1
    $assemblyPath = Join-Path $packageFolder ($library.Value.path + "\lib\net472\Microsoft.VisualStudio.ImageCatalog.dll")
    if (-not (Test-Path $assemblyPath)) {
        $assemblyPath = Get-ChildItem (Join-Path $packageFolder $library.Value.path) -Recurse -Filter Microsoft.VisualStudio.ImageCatalog.dll |
            Select-Object -First 1 -ExpandProperty FullName
    }

    if (-not $assemblyPath) {
        return $null
    }

    $assembly = [System.Reflection.Assembly]::LoadFrom($assemblyPath)
    $type = $assembly.GetType("Microsoft.VisualStudio.Imaging.KnownMonikers", $true)
    return @($type.GetProperties([System.Reflection.BindingFlags]"Public,Static").Name)
}

function Import-LegacyCatalog {
    $legacyManifest = if ($LegacyManifestPath) { $LegacyManifestPath } else { $manifestPath }
    $legacyPkgdef = if ($LegacyPkgdefPath) { $LegacyPkgdefPath } else { $pkgdefPath }
    $manifest = [xml](Get-Content $legacyManifest -Raw)
    $namespace = [System.Xml.XmlNamespaceManager]::new($manifest.NameTable)
    $namespace.AddNamespace("i", $manifest.DocumentElement.NamespaceURI)

    $guid = $manifest.SelectSingleNode("//i:Symbols/i:Guid[@Name='MonikersGuid']", $namespace).Value.Trim("{}")
    $symbols = @{}
    $usedIds = @{}
    $nextId = 0
    $images = @()

    foreach ($symbol in $manifest.SelectNodes("//i:Symbols/i:ID", $namespace)) {
        $id = [int]$symbol.Value
        if ($usedIds.ContainsKey($id)) {
            while ($usedIds.ContainsKey($nextId)) {
                $nextId++
            }
            $id = $nextId
        }

        $symbols[$symbol.Name] = $id
        $usedIds[$id] = $symbol.Name
        $nextId = [Math]::Max($nextId, $id + 1)

        $imageNode = $manifest.SelectSingleNode("//i:Image[@ID='`$($($symbol.Name))']", $namespace)
        $sourceNode = $imageNode.SelectSingleNode("i:Source", $namespace)
        $sizeNode = $sourceNode.SelectSingleNode("i:Size", $namespace)
        $dimensionsNode = $sourceNode.SelectSingleNode("i:Dimensions", $namespace)

        $image = [ordered]@{
            name = $symbol.Name
            id = $id
            file = Split-Path $sourceNode.Uri -Leaf
            provenance = "legacy-unverified"
        }

        if ($sizeNode) {
            $image.size = [int]$sizeNode.Value
        }
        elseif ($dimensionsNode) {
            $image.width = [int]$dimensionsNode.Width
            $image.height = [int]$dimensionsNode.Height
        }

        $images += [pscustomobject]$image
    }

    $associations = @{}
    $category = "General"
    $extension = $null

    foreach ($line in Get-Content $legacyPkgdef) {
        if ($line -match "^;\s*(?<category>.*?)\s*$") {
            $candidate = $Matches.category.Trim().TrimEnd(";").Trim()
            if ($candidate -and
                $candidate -notmatch "^-+$" -and
                $candidate -notlike "Find supported icons*" -and
                $candidate -notlike "Generated by*") {
                $category = $candidate
            }
        }
        elseif ($line -match "^\[\`$RootKey\`$\\ShellFileAssociations\\(?<extension>[^\]]+)\]$") {
            $extension = $Matches.extension.ToLowerInvariant()
        }
        elseif ($extension -and $line -match '^"DefaultIconMoniker"="(?<moniker>[^"]+)"$') {
            $entry = [ordered]@{
                extension = $extension
                category = $category
            }

            $moniker = $Matches.moniker
            if ($moniker -match "^[0-9a-f-]+:(?<id>\d+)$") {
                $matchingImages = @($images | Where-Object { $_.id -eq [int]$Matches.id -or
                    ($_.name -eq $category.Replace(" ", "").ToLowerInvariant()) })
                $selectedImage = $matchingImages |
                    Sort-Object @{ Expression = { $_.name -ne $category.Replace(" ", "").ToLowerInvariant() } } |
                    Select-Object -First 1
                if (-not $selectedImage) {
                    throw "No custom image found for $extension ($moniker)."
                }
                $entry.image = $selectedImage.name
            }
            else {
                $entry.moniker = $moniker
            }

            $associations[$extension] = [pscustomobject]$entry
            $extension = $null
        }
    }

    $catalog = [ordered]@{
        schemaVersion = 1
        customMonikerGuid = $guid
        customImages = @($images | Sort-Object id, name)
        associations = @($associations.Values | Sort-Object category, extension)
    }

    [System.IO.File]::WriteAllText(
        $catalogPath,
        (($catalog | ConvertTo-Json -Depth 8) + "`r`n"),
        $utf8)
}

if ($ImportLegacy) {
    Import-LegacyCatalog
}

if (-not (Test-Path $catalogPath)) {
    throw "Catalog not found: $catalogPath"
}

$catalog = Get-Content $catalogPath -Raw | ConvertFrom-Json
if ($catalog.schemaVersion -ne 1) {
    throw "Unsupported catalog schema version: $($catalog.schemaVersion)"
}

$duplicateExtensions = @($catalog.associations | Group-Object extension | Where-Object Count -gt 1)
if ($duplicateExtensions) {
    throw "Duplicate extensions: $($duplicateExtensions.Name -join ', ')"
}

$duplicateImageNames = @($catalog.customImages | Group-Object name | Where-Object Count -gt 1)
if ($duplicateImageNames) {
    throw "Duplicate custom image names: $($duplicateImageNames.Name -join ', ')"
}

$duplicateImageIds = @($catalog.customImages | Group-Object id | Where-Object Count -gt 1)
if ($duplicateImageIds) {
    throw "Duplicate custom image IDs: $($duplicateImageIds.Name -join ', ')"
}

$knownMonikers = Get-KnownMonikerNames
$imageByName = @{}
foreach ($image in $catalog.customImages) {
    if ($image.id -lt 0) {
        throw "Custom image '$($image.name)' has a negative ID."
    }

    $imagePath = Join-Path $srcRoot ("Icons\" + $image.file)
    if (-not (Test-Path $imagePath)) {
        throw "Custom image file is missing: $imagePath"
    }

    $imageExtension = [System.IO.Path]::GetExtension($image.file).ToLowerInvariant()
    if ($imageExtension -notin ".png", ".xaml") {
        throw "Custom image '$($image.name)' must use a PNG or XAML file."
    }

    if ($imageExtension -eq ".png" -and
        -not $image.size -and
        (-not $image.width -or -not $image.height)) {
        throw "PNG image '$($image.name)' must specify size or width and height."
    }

    if ($imageExtension -eq ".xaml") {
        if ($image.size -or $image.width -or $image.height) {
            throw "XAML image '$($image.name)' must be size-neutral and omit raster dimensions."
        }

        try {
            $null = [xml](Get-Content $imagePath -Raw)
        }
        catch {
            throw "XAML image '$($image.name)' is not well-formed XML: $($_.Exception.Message)"
        }
    }

    if (-not $image.provenance) {
        throw "Custom image '$($image.name)' has no provenance."
    }

    if ($image.provenance -ne "legacy-unverified" -and
        ([string]::IsNullOrWhiteSpace($image.source) -or [string]::IsNullOrWhiteSpace($image.license))) {
        throw "Verified custom image '$($image.name)' must specify source and license."
    }

    $imageByName[$image.name] = $image
}

$catalogImageFiles = @($catalog.customImages.file | Sort-Object -Unique)
$diskImageFiles = @(Get-ChildItem (Join-Path $srcRoot "Icons") -File |
    Where-Object Extension -in ".png", ".xaml" |
    Select-Object -ExpandProperty Name)
$unlistedImageFiles = @($diskImageFiles | Where-Object { $_ -notin $catalogImageFiles })
if ($unlistedImageFiles) {
    throw "Image files are not listed in the catalog: $($unlistedImageFiles -join ', ')"
}

foreach ($association in $catalog.associations) {
    if ($association.extension -cnotmatch "^\.[a-z0-9][a-z0-9._+-]*$") {
        throw "Invalid or non-normalized extension: $($association.extension)"
    }

    $hasMoniker = -not [string]::IsNullOrWhiteSpace($association.moniker)
    $hasImage = -not [string]::IsNullOrWhiteSpace($association.image)
    if ($hasMoniker -eq $hasImage) {
        throw "Association '$($association.extension)' must specify exactly one of moniker or image."
    }

    if ($hasImage -and -not $imageByName.ContainsKey($association.image)) {
        throw "Association '$($association.extension)' references unknown image '$($association.image)'."
    }

    if ($hasMoniker -and $association.moniker -notmatch "^KnownMonikers\.(?<name>[A-Za-z0-9_]+)$") {
        throw "Association '$($association.extension)' has an invalid moniker '$($association.moniker)'."
    }

    if ($hasMoniker -and $knownMonikers -and $Matches.name -notin $knownMonikers) {
        throw "Association '$($association.extension)' references missing moniker '$($association.moniker)'."
    }
}

$referencedImages = @($catalog.associations.image | Where-Object { $_ } | Sort-Object -Unique)
$unreferencedImages = @($catalog.customImages | Where-Object name -notin $referencedImages)
if ($unreferencedImages) {
    throw "Unreferenced custom images: $($unreferencedImages.name -join ', ')"
}

$guid = $catalog.customMonikerGuid.Trim("{}")
$pkgdef = [System.Text.StringBuilder]::new()
$null = $pkgdef.AppendLine("; Generated by tools\Generate-Catalog.ps1. Do not edit manually.")
$null = $pkgdef.AppendLine()
foreach ($group in $catalog.associations | Group-Object category) {
    $null = $pkgdef.AppendLine("; $($group.Name)")
    foreach ($association in $group.Group | Sort-Object extension) {
        $moniker = $association.moniker
        if ($association.image) {
            $moniker = "$guid`:$($imageByName[$association.image].id)"
        }

        $null = $pkgdef.AppendLine("[`$RootKey`$\ShellFileAssociations\$($association.extension)]")
        $null = $pkgdef.AppendLine("`"DefaultIconMoniker`"=`"$moniker`"")
    }
    $null = $pkgdef.AppendLine()
}

$manifest = [System.Text.StringBuilder]::new()
$null = $manifest.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
$null = $manifest.AppendLine('<ImageManifest xmlns="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014">')
$null = $manifest.AppendLine('  <Symbols>')
$null = $manifest.AppendLine('    <String Name="Resources" Value="/FileIcons;Component/Icons" />')
$null = $manifest.AppendLine("    <Guid Name=`"MonikersGuid`" Value=`"{$guid}`" />")
foreach ($image in $catalog.customImages | Sort-Object id, name) {
    $null = $manifest.AppendLine("    <ID Name=`"$($image.name)`" Value=`"$($image.id)`" />")
}
$null = $manifest.AppendLine('  </Symbols>')
$null = $manifest.AppendLine('  <Images>')
foreach ($image in $catalog.customImages | Sort-Object id, name) {
    $null = $manifest.AppendLine("    <Image Guid=`"`$(MonikersGuid)`" ID=`"`$($($image.name))`">")
    if ($image.size) {
        $null = $manifest.AppendLine("      <Source Uri=`"`$(Resources)/$($image.file)`">")
        $null = $manifest.AppendLine("        <Size Value=`"$($image.size)`" />")
        $null = $manifest.AppendLine('      </Source>')
    }
    elseif ($image.width -and $image.height) {
        $null = $manifest.AppendLine("      <Source Uri=`"`$(Resources)/$($image.file)`">")
        $null = $manifest.AppendLine("        <Dimensions Width=`"$($image.width)`" Height=`"$($image.height)`" />")
        $null = $manifest.AppendLine('      </Source>')
    }
    else {
        $null = $manifest.AppendLine("      <Source Uri=`"`$(Resources)/$($image.file)`" />")
    }
    $null = $manifest.AppendLine('    </Image>')
}
$null = $manifest.AppendLine('  </Images>')
$null = $manifest.AppendLine('</ImageManifest>')

$extensions = @($catalog.associations.extension | Sort-Object -Unique)
$extensionDocument = "## Supported File Extensions ($($extensions.Count))`r`n`r`n" +
    (($extensions | ForEach-Object { "- $_" }) -join "`r`n")

Write-GeneratedFile $pkgdefPath $pkgdef.ToString()
Write-GeneratedFile $manifestPath $manifest.ToString()
Write-GeneratedFile $extensionsPath $extensionDocument

Write-Host "Validated $($extensions.Count) associations and $($catalog.customImages.Count) custom images."
