// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileIcons
{
    static class Vsix
    {
        public const string Id = "3a7b4930-a5fb-46ec-a9b8-9610c8f953b8";
        public const string Name = "File Icons";
        public const string Description = @"Adds icons for files that are not recognized by Solution Explorer";
        public const string Language = "en-US";
        public const string Version = "1.10";
        public const string Author = "Mads Kristensen";
        public const string Tags = "icon, file, image";
    }
}
